steps:
  pytest:
    image: "python:${TAG}"
    commands:
      - apt-get update && apt-get install -y libidn11-dev
      - git clone https://lab.louiz.org/poezio/slixmpp.git
      - pip3 install pytest pyasn1-modules cffi --upgrade
      - cd slixmpp
      - python3 setup.py install
      - cd ..
      - python3 setup.py install
      - py.test -v test/

matrix:
  TAG:
    - "3.7"
    - "3.9"
    - "3.8"
    - "3.10"
    - "3.11"
    - "3.12-rc"
